### ISSUE TITLE
GET /account uses body

### ISSUE THREAD

**Issue by ngagesmu** [ngagesmu/S2021_Team5_Dev#50]
It is not possible to send a body in a GET request due to browser HTTP client limitations.

Functionality should be added to current `GET "/users?role_id={role_id}"`:

So final route would be:
`GET "/users?user_id={user_id}&role_id={role_id}"`

**Comment by znew10** [comment]
I didn't use body, I set it as params. I don't understand what's the point of using the role_id if you're just gonna enter the user_id as well.

**Comment by znew10** [comment]
I can add another get request that's more in depth if u want tho

**Comment by ngagesmu** [comment]
the GET /users route is good, that's one with params

The GET /account route on main branch uses GET with a json body, that's the one that should just be dropped for another optional param on GET /users

As for why, you could do `GET /users?user_id=4` if you want to get one user's information since the params are optional, or actually what might be better convention is `GET /users/:user_id`. I just need a way to get a single user by an their ID, and certain browsers can't send GET w/ body so I figured you could add that to the route you already made.

**Comment by znew10** [comment]
Oh I see now. Yea I'll fix that for you.
